# Generated by Django 5.0.1 on 2024-03-13 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='croppreservation',
            name='Crop_image',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to=''),
        ),
    ]
