# Generated by Django 5.0.1 on 2024-03-13 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_croppreservation_crop_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='croppreservation',
            name='Crop_Temp',
            field=models.CharField(blank=True, null=True),
        ),
    ]
