# Generated by Django 5.0.1 on 2024-03-16 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_fertilizer_product_alter_croppreservation_crop_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fertilizer_product',
            name='Description',
            field=models.TextField(max_length=80),
        ),
    ]
