# Generated by Django 5.0.1 on 2024-03-16 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_fertilizer_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fertilizer_product',
            name='Description',
            field=models.TextField(max_length=120),
        ),
    ]
