# Generated by Django 5.0.1 on 2024-03-18 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_addtocart'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoilTesting_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Laboratory_Number', models.CharField(max_length=100)),
                ('Farmer_Name', models.CharField(max_length=100)),
                ('Village', models.CharField(max_length=100)),
                ('Survey_Number', models.CharField(max_length=100)),
                ('Taluka_District', models.CharField(max_length=100)),
                ('Test', models.CharField(max_length=100)),
                ('Proporstion', models.CharField(max_length=100)),
                ('P_H_Number', models.CharField(max_length=100)),
                ('Electrical_Conductivity', models.CharField(max_length=100)),
                ('Organic_carbon', models.CharField(max_length=100)),
                ('Avalaible_PhosPhorus', models.CharField(max_length=100)),
                ('Avalaible_Potas', models.CharField(max_length=100)),
                ('Micro_Element', models.CharField(max_length=100)),
                ('Analysis', models.CharField(max_length=100)),
                ('Quality', models.CharField(max_length=100)),
                ('Zinc', models.CharField(max_length=100)),
                ('Cooper', models.CharField(max_length=100)),
                ('Magananese', models.CharField(max_length=100)),
                ('Brimstone', models.CharField(max_length=100)),
                ('Boron', models.CharField(max_length=100)),
                ('Lime', models.CharField(max_length=100)),
                ('Gypsum', models.CharField(max_length=100)),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user_registration')),
            ],
        ),
    ]
