# Generated by Django 5.0.1 on 2024-03-18 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_soiltesting_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soiltesting_table',
            name='Analysis',
        ),
        migrations.RemoveField(
            model_name='soiltesting_table',
            name='Micro_Element',
        ),
        migrations.RemoveField(
            model_name='soiltesting_table',
            name='Proporstion',
        ),
        migrations.RemoveField(
            model_name='soiltesting_table',
            name='Quality',
        ),
        migrations.RemoveField(
            model_name='soiltesting_table',
            name='Test',
        ),
    ]
