# Generated by Django 5.0.1 on 2024-03-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_soiltesting_table_analysis_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soiltesting_table',
            name='Avalaible_PhosPhorus',
        ),
        migrations.RemoveField(
            model_name='soiltesting_table',
            name='Avalaible_Potas',
        ),
        migrations.RemoveField(
            model_name='soiltesting_table',
            name='Boron',
        ),
        migrations.RemoveField(
            model_name='soiltesting_table',
            name='Brimstone',
        ),
        migrations.RemoveField(
            model_name='soiltesting_table',
            name='Cooper',
        ),
        migrations.RemoveField(
            model_name='soiltesting_table',
            name='Electrical_Conductivity',
        ),
        migrations.RemoveField(
            model_name='soiltesting_table',
            name='Gypsum',
        ),
        migrations.RemoveField(
            model_name='soiltesting_table',
            name='Lime',
        ),
        migrations.RemoveField(
            model_name='soiltesting_table',
            name='Magananese',
        ),
        migrations.RemoveField(
            model_name='soiltesting_table',
            name='Organic_carbon',
        ),
        migrations.RemoveField(
            model_name='soiltesting_table',
            name='P_H_Number',
        ),
        migrations.RemoveField(
            model_name='soiltesting_table',
            name='Zinc',
        ),
        migrations.AddField(
            model_name='soiltesting_table',
            name='Avalaible_PhosPhorus_Proporstion',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='soiltesting_table',
            name='Avalaible_PhosPhorus_Quality',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='soiltesting_table',
            name='Avalaible_Potas_Proporstion',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='soiltesting_table',
            name='Avalaible_Potas_Quality',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='soiltesting_table',
            name='Boron_Analysis',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='soiltesting_table',
            name='Boron_Quality',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='soiltesting_table',
            name='Brimstone_Analysis',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='soiltesting_table',
            name='Brimstone_Quality',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='soiltesting_table',
            name='Cooper_Analysis',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='soiltesting_table',
            name='Cooper_Quality',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='soiltesting_table',
            name='Electrical_Conductivity_Proporstion',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='soiltesting_table',
            name='Electrical_Conductivity_Quality',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='soiltesting_table',
            name='Gypsum_Analysis',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='soiltesting_table',
            name='Gypsum_Quality',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='soiltesting_table',
            name='Lime_Analysis',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='soiltesting_table',
            name='Lime_Quality',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='soiltesting_table',
            name='Magananese_Analysis',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='soiltesting_table',
            name='Magananese_Quality',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='soiltesting_table',
            name='Organic_carbon_Proporstion',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='soiltesting_table',
            name='Organic_carbon_Quality',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='soiltesting_table',
            name='P_H_Number_Proporstion',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='soiltesting_table',
            name='P_H_Number_Quality',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='soiltesting_table',
            name='Zinc_Analysis',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='soiltesting_table',
            name='Zinc_Quality',
            field=models.CharField(default='Null', max_length=100),
        ),
    ]
