# Generated by Django 5.0.1 on 2024-03-19 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_soiltesting_table_avalaible_phosphorus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addtocart',
            name='Quantity',
        ),
    ]
