# Generated by Django 5.0.1 on 2024-03-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_addtocart_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeedsInFo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Seed_Name', models.CharField(max_length=100)),
                ('Seed_Description', models.TextField(max_length=50)),
                ('Seed_image', models.ImageField(default=None, null=True, upload_to='')),
            ],
        ),
    ]
