# Generated by Django 5.0.1 on 2024-03-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_seedsinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='seedsinfo',
            name='Seed_Type',
            field=models.CharField(choices=[('Monocotyledonous seeds', 'Monocotyledonous seeds'), ('Dicotyledonous seeds', 'Dicotyledonous seeds')], default='null'),
        ),
    ]
