# Generated by Django 5.0.1 on 2024-03-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_seedsinfo_seed_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seedsinfo',
            name='Seed_Description',
            field=models.TextField(max_length=150),
        ),
    ]
