# Generated by Django 5.0.1 on 2024-03-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_seedsinfo_seed_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Govermentschem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titel', models.CharField(max_length=100)),
                ('Description', models.TextField(default=None, max_length=150, null=True)),
                ('Link', models.CharField(max_length=250)),
                ('Publish_Date', models.DateField()),
            ],
        ),
    ]
