# Generated by Django 5.0.1 on 2024-03-25 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_govermentschem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='govermentschem',
            old_name='Titel',
            new_name='Title',
        ),
    ]
