# Generated by Django 5.0.1 on 2024-03-29 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_seedsinfo_seed_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seedsinfo',
            name='Seed_Type',
            field=models.CharField(choices=[('Grains seeds', 'Grains seeds'), ('Pulses seeds', 'Pulses seeds'), ('Oilseeds seeds', 'Oilseeds seeds'), ('Vegetables seeds', 'Vegetables seeds'), ('Spices seeds', 'Spices  seeds')], default='null'),
        ),
    ]
